<div class="updatetitle">
	Updates</div>
<div class="divider"></div>
<center><h4><a href="result.php">Pool A wins Takneek!</a></h4></center>
<div class="divider"></div>
<center><h5><a href="points.php">Competitions Points Break-up</a></h5></center>
<div class="divider"></div>
<center><h5><a href="http://students.iitk.ac.in/bclub/wp/">"La Soci&#233;t&#233; de Affair&#233;s"</a></h5></center>
<p>The Business Club online newsletter</p>
