Website designed by <a href="mailto:chirags@iitk.ac.in">Chirag Sangani</a>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-10671167-1");
pageTracker._trackPageview();
} catch(err) {}</script>
<script type="text/javascript">
var sc_project=5116891; 
var sc_invisible=1; 
var sc_partition=58; 
var sc_click_stat=1; 
var sc_security="ba250a7e"; 
</script>
<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
class="statcounter"><a title="myspace profile counters"
href="http://www.statcounter.com/myspace/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/5116891/0/ba250a7e/1/"
alt="myspace profile counters" ></a></div></noscript>