<meta content="text/html; charset=utf-8" http-equiv="content-type" />
<meta content="index, follow" name="robots" />
<meta content="takneek, techkriti, iit, iitk, kanpur, iitkanpur, electronics, robotics, programming, ham, aeromodelling, club, scitech, competition" name="keywords" />
<meta content="Takneek is the inter-hall SciTech competition of IIT Kanpur." name="description" />
<meta content="Chirag Sangani, chirags@iitk.ac.in" name="designer" />
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<script src="js/mootools.js" type="text/javascript"></script>
<script src="js/mootools-more.js" type="text/javascript"></script>
<script src="js/takmenu.js" type="text/javascript"></script>
<link href="css/common.css" rel="stylesheet" type="text/css" />
<link rel="icon" type="image/png" href="images/favicon.png" />
