<ul id="dropdownmenu">
	<li class="menu">
	<div class="mainmenuitem">
		<a href="./"><span class="mainmenutitle">Home</span><span class="mainmenusubtitle">Takneek</span></a></div>
		<ul class="links"></ul>
	</li>
	<li class="menu">
	<div class="mainmenuitem">
		<a href="competitions.php"><span class="mainmenutitle">Competitions</span><span class="mainmenusubtitle">Problem Statements</span></a></div>
	<ul class="links">
		<li class="droptop"></li>
		<li>
		<div>
			<a href="rube.php">Rube Goldberg</a></div>
		</li>
		<li>
		<div>
			<a href="nirmaan.php">Nirmaan</a></div>
		</li>
		<li>
		<div>
			<a href="scimatex.php">Scimatex</a></div>
		</li>
		<li>
		<div>
			<a href="boomerang.php">Boomerang</a></div>
		</li>
		<li>
		<div>
			<a href="pushpak.php">Pushpak</a></div>
		</li>
		<li>
		<div>
			<a href="astroevents.php">Astro Events</a></div>
		</li>
		<li> 
		<div> 
			<a href="casino.php">Slot Machine</a></div>
		</li>
		<li> 
		<div> 
			<a href="touchpad.php">Touchpad</a></div>
		</li>
		<li> 
		<div>
			<a href="foxhunt.php">Foxhunt</a></div>
		</li>
		<li> 
		<div>
			<a href="gameprogram.php">Game Programming</a></div>
		</li>
		<li> 
		<div>
			<a href="gearloose.php">Gearloose</a></div>
		</li>
		<li>
		<div>
			<a href="safari.php">Ultimate Safari</a></div>
		</li>
		<li>
		<div> 
			<a href="victorytower.php">Victory Tower</a></div>
		</li>
		<li>
		<div> 
			<a href="rubik.php">Rubik's Cube</a></div>
		</li>
		
		<li class="dropbot"></li>
	</ul>
	</li>
	<li class="menu">
	<div class="mainmenuitem">
		<a><span class="mainmenutitle">Events</span><span class="mainmenusubtitle">Workshops &amp; Talks</span></a></div>
	<ul class="links">
		<li class="droptop"></li>
		<li>
		<div>
			<a href="scicomm.php">Science Communication</a></div>
		</li>
		<li>
		<div>
			<a href="scientoons.php">Scientoons</a></div>
		</li>
		<li>
		<div>
			<a href="thandling.php">Telescope Handling</a></div>
		</li>		
		<li class="dropbot"></li>
	</ul>
	</li>
	<li class="menu">
	<div class="mainmenuitem">
		<a href="schedule.php"><span class="mainmenutitle">Schedule</span><span class="mainmenusubtitle">Event Timings</span></a></div>
	<ul class="links">
	</ul>
	</li>
	<li class="menu">
	<div class="mainmenuitem">
		<a href="gallery.php"><span class="mainmenutitle">Gallery</span><span class="mainmenusubtitle">Pics &amp; Vids</span></a></div>
	<ul class="links">
	</ul>
	</li>
	<li class="menu">
	<div class="mainmenuitem">
		<a href="contacts.php"><span class="mainmenutitle">Contacts</span><span class="mainmenusubtitle">Coordinators</span></a></div>
	<ul class="links"></ul>
	</li>
</ul>