<div class="block">
	<div class="block-t">
		<div class="block-r">
			<div id="announcements-wrapper" class="block-l">
				<div id="announcements-text">
				</div>
				<ul id="announcement-ul">
					<li class="announcement-li">New Website: To be updated soon!</li>
					<li class="announcement-li">Embedded material uploaded: check Database.</li>
					<li class="announcement-li">Old website accessible here: <a href="./old">Old Electronics Club Website</a></li>
					<li id="announcement-end" class="announcement-li"></li>
				</ul>
				<div class="clear"></div>
			</div>
		</div>
	</div>
</div>
