<div id="footer-wrapper">
	<div class="block">
		<div class="block-t">
			<div class="block-r">
				<div id="footer" class="block-l">
					<div id="footerimg">
						<span id="footer-nodisp">Electronics Club, Indian Institute 
						of Technology Kanpur. Designed by Chirag Sangani.</span>
						<a id="footer-cs-link" href="http://www.chiragsangani.com">
						</a></div>
					<div class="clear">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
