<div class="block">
	<div class="block-t">
		<div class="block-r">
			<div id="header-wrapper" class="block-l">
				<div id="logo">
					<a id="logolink" href="./"></a></div>
				<div id="menubar">
					<div id="home" class="menublock">
						<a class="menulink" href="./"></a></div>
					<div id="database" class="menublock">
						<a class="menulink" href="./database.php"></a></div>
					<div id="projects" class="menublock">
						<a class="menulink" href="./projects.php"></a></div>
					<div id="gallery" class="menublock">
						<a class="menulink" href="./gallery.php"></a></div>
					<div id="links" class="menublock">
						<a class="menulink" href="./links.php"></a></div>
					<div id="contact" class="menublock">
						<a class="menulink" href="./contact.php"></a></div>
					<div id="search" class="menublock">
						<a id="searchbutton" class="menulink"></a>
						<div id="search-form">
							<form id="search-form1" action="#">
								<div><input id="search-input" type="text" /></div></form>
&nbsp;</div>
					</div>
				</div>
				<div id="tagbar">
					<div id="motto" class="tag">
					</div>
<div id="database-tag" class="tag">
					</div>
<div id="projects-tag" class="tag">
					</div>
<div id="gallery-tag" class="tag">
					</div>
<div id="links-tag" class="tag">
					</div>
<div id="contact-tag" class="tag">
					</div>
					
					</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
</div>
