<meta content="text/html; charset=utf-8" http-equiv="content-type" />
<meta content="index, follow" name="robots" />
<meta content="eclub, iit, iitk, kanpur, iitkanpur, club, event, electronics, snt, science, technology, competition, embedded, digital, analog, takneek, techkriti, electrovate" name="keywords" />
<meta content="Electronics Club at IIT Kanpur is a hobby group of enthusiasts who explore modern-day electronics." name="description" />
<meta content="Chirag Sangani, chirags@iitk.ac.in" name="designer" />
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script src="js/jquery.js" type="text/javascript"></script>
<script src="js/effects.js" type="text/javascript"></script>
<link href="css/common.css" rel="stylesheet" type="text/css" />
<link href="css/default.css" rel="stylesheet" type="text/css" />
<link href="./images/favicon.png" rel="icon" type="image/png" />
